name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_DIR }}
          git pull origin main
          source scripts/setup_nvm.sh
          pnpm install --prod
          pnpm build
          nohup pnpm start > /dev/null 2>&1 &
